apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "client"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: client
          image: ghcr.io/dazwilkin/dapr-grpc-client@sha256:271497f6bc0df1ed506d02265caf83ebdfa200865295917690d8818719d622cc
          args:
            - --app=server.example
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
