apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "client"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: app
          image: ghcr.io/dazwilkin/dapr-grpc-client:v0.0.2
          args:
            - --app=server
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
