apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "server"
        dapr.io/app-protocol: "grpc"
        dapr.io/app-port: "50051"
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: app
          image: ghcr.io/dazwilkin/dapr-grpc-server:v0.0.2
          args:
            - --port=50051
          resources:
            limits:
              cpu: "100m"
              memory: "25Mi"
