name: containers

on:
  push:
    branches:
      - master

jobs:
  server:
    name: server
    runs-on: ubuntu-20.04
    env:
      REPO: dazwilkin/dapr-grpc-example
      VERS: v0.0.2
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deployment/Dockerfile.server
          tags: ghcr.io/${{ env.REPO }}:${{ env.VERS }}
          push: true
  client:
    name: client
    runs-on: ubuntu-20.04
    env:
      REPO: dazwilkin/dapr-grpc-example
      VERS: v0.0.2
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deployment/Dockerfile.client
          tags: ghcr.io/${{ env.REPO }}:${{ env.VERS }}
          push: true
